### Registro
POST http://localhost:3333/user/register
Content-Type: application/json

{
    "password": "admin",
    "username": "admin",
    "is_admin": true
}

### Registro
POST http://localhost:3333/user/register
Content-Type: application/json

{
    "password": "bruno",
    "username": "bruno",
    "is_admin": false
}